-- ==========================================
-- SUPABASE SCHEMA UNTUK NGOPI GAK APP
-- ==========================================

-- 1. Table: sessions
CREATE TABLE IF NOT EXISTS public.sessions (
    id TEXT PRIMARY KEY,
    status TEXT DEFAULT 'open',
    started_by TEXT,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    payer TEXT,
    companion TEXT,
    payment_method TEXT,
    bank_name TEXT,
    account_no TEXT,
    coffee_bought BOOLEAN DEFAULT FALSE,
    coffee_bought_at TIMESTAMPTZ,
    force_closed_by TEXT,
    debtors TEXT[] DEFAULT '{}'
);

-- 2. Table: orders
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES public.sessions(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    coffee_id TEXT,
    coffee_name TEXT,
    coffee_price INTEGER,
    coffee_emoji TEXT,
    is_paid BOOLEAN DEFAULT FALSE,
    marked_by_payer BOOLEAN DEFAULT FALSE
);

-- 3. Table: notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    target_user TEXT NOT NULL,
    type TEXT,
    message TEXT,
    is_read_by TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: menu_items
CREATE TABLE IF NOT EXISTS public.menu_items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    emoji TEXT
);

-- 5. Table: payer_history
CREATE TABLE IF NOT EXISTS public.payer_history (
    username TEXT PRIMARY KEY,
    pay_count INTEGER DEFAULT 0
);

-- 6. Table: historic_sessions
CREATE TABLE IF NOT EXISTS public.historic_sessions (
    id TEXT PRIMARY KEY,
    data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- MENGAKTIFKAN SUPABASE REALTIME
-- ==========================================
-- Aplikasi menggunakan event postgres_changes untuk sinkronisasi state secara real-time.
-- Kita perlu menambahkan tabel-tabel ini ke dalam publication supabase_realtime.

-- Tambahkan tabel ke publication
-- Catatan: Jika saat di-run muncul peringatan "relation already exists", biarkan saja (itu aman).
ALTER PUBLICATION supabase_realtime ADD TABLE 
    public.sessions, 
    public.orders, 
    public.notifications, 
    public.menu_items, 
    public.payer_history, 
    public.historic_sessions;

-- ==========================================
-- DISABLE RLS (UNTUK SEMENTARA / PROTOTYPE)
-- ==========================================
-- Karena aplikasi ini menggunakan access control melalui front-end (tanpa user auth Supabase),
-- kita harus memastikan RLS (Row Level Security) false atau memberikan allow-all policy agar 
-- anon key bisa melakukan read/write tanpa dilarang.
-- (Lebih baik matikan RLS agar Anon key dari frontend memiliki hak akses penuh selama masa testing).

ALTER TABLE public.sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payer_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.historic_sessions DISABLE ROW LEVEL SECURITY;
